"""
TO WRITE LATER - AT SOME STAGE WE WILL NEED AN OVERFLOW TEST, TO TEST OVERFLOW EMPIRICALLY, WE CAN SET ALL OF THE CAPACITIES TO 1 AND SEE IF ANY STRANGE BEHAVIOURS OCCUR, FIGURE OUT A WAY TO MAKE THIS MORE OBJECTIVE
"""